# travis rules for vision_utils
# use Ubuntu Trusty 14.04, compatible with ROS Indigo - check https://docs.travis-ci.com/user/ci-environment/
sudo: required
dist: trusty

language: cpp
compiler:
  - gcc

before_install:
  # install ROS according to http://wiki.ros.org/indigo/Installation/Ubuntu
  - export ROS_DISTRO=indigo
  - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu trusty main" > /etc/apt/sources.list.d/ros-latest.list'
  - wget https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -O - | sudo apt-key add -
  - sudo apt-get -qq update
  - sudo apt-get install -y -qq  ros-$ROS_DISTRO-ros-base  ros-$ROS_DISTRO-cv-bridge  ros-$ROS_DISTRO-image-geometry  ros-$ROS_DISTRO-image-transport  ros-$ROS_DISTRO-pcl-ros  ros-$ROS_DISTRO-rosbag ros-$ROS_DISTRO-sensor-msgs  ros-$ROS_DISTRO-std-msgs
  - source /opt/ros/$ROS_DISTRO/setup.bash
  # fix a bug with catkin_pkg - cf. http://answers.ros.org/question/56873/problem-with-catkin_make/
  - export PYTHONPATH="$PYTHONPATH:/usr/lib/python2.7/dist-packages"

before_script: #  Use this to prepare your build for testing e.g. copy database configurations, environment variables, etc.
  # Create catkin workspace
  - export CI_SOURCE_PATH=$(pwd)
  - mkdir -p ~/catkin_ws/src
  - cd ~/catkin_ws/src
  - catkin_init_workspace
  - ln -s $CI_SOURCE_PATH . # Link the repo we are testing to the new workspace

script: # compile
  - cd ~/catkin_ws
  - catkin_make
