CC=g++
PATH_AD = $(AD_HOME)

PATH_INSTALL = $(PATH_AD)/robot/bin/utils/xml/
PATH_INCLUDE =  $(PATH_AD)/robot/include/
PATH_LIBRARY = $(PATH_AD)/robot/lib/



install:
	cp *.h $(PATH_INCLUDE)
	mkdir -p $(PATH_INSTALL)

